/*
 * generated by Xtext
 */
package org.xtext.example.statemachine.validation
import org.eclipse.xtext.validation.Check
import org.xtext.example.statemachine.statemachine.Statemachine
import org.xtext.example.statemachine.statemachine.StatemachinePackage
import org.xtext.example.statemachine.statemachine.State

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class StatemachineValidator extends AbstractStatemachineValidator {

	@Check
	def void checkStatesNotDuplicated(State s){
		for( other: (s.eContainer as Statemachine).states ){
			if( (s != other) && s.name.toString.equals( other.name.toString) ){
				warning("State names have to be unique", StatemachinePackage.Literals.STATE__NAME);	
			}
		}
	}
}
