/**
 * generated by Xtext
 */
package org.xtext.example.statemachine.ui.contentassist;

import org.xtext.example.statemachine.ui.contentassist.AbstractStatemachineProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class StatemachineProposalProvider extends AbstractStatemachineProposalProvider {
}
