/*
* generated by Xtext
*/
package org.xtext.example.statemachine.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.statemachine.services.StatemachineGrammarAccess;

public class StatemachineParser extends AbstractContentAssistParser {
	
	@Inject
	private StatemachineGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.statemachine.ui.contentassist.antlr.internal.InternalStatemachineParser createParser() {
		org.xtext.example.statemachine.ui.contentassist.antlr.internal.InternalStatemachineParser result = new org.xtext.example.statemachine.ui.contentassist.antlr.internal.InternalStatemachineParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getStatemachineAccess().getGroup(), "rule__Statemachine__Group__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getStatemachineAccess().getNameAssignment_1(), "rule__Statemachine__NameAssignment_1");
					put(grammarAccess.getStatemachineAccess().getStatesAssignment_5(), "rule__Statemachine__StatesAssignment_5");
					put(grammarAccess.getStatemachineAccess().getEventsAssignment_9(), "rule__Statemachine__EventsAssignment_9");
					put(grammarAccess.getStatemachineAccess().getTransitionsAssignment_13(), "rule__Statemachine__TransitionsAssignment_13");
					put(grammarAccess.getStatemachineAccess().getInitialiStateAssignment_16(), "rule__Statemachine__InitialiStateAssignment_16");
					put(grammarAccess.getStateAccess().getNameAssignment(), "rule__State__NameAssignment");
					put(grammarAccess.getEventAccess().getNameAssignment(), "rule__Event__NameAssignment");
					put(grammarAccess.getTransitionAccess().getFromAssignment_0(), "rule__Transition__FromAssignment_0");
					put(grammarAccess.getTransitionAccess().getEventAssignment_2(), "rule__Transition__EventAssignment_2");
					put(grammarAccess.getTransitionAccess().getToAssignment_4(), "rule__Transition__ToAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.statemachine.ui.contentassist.antlr.internal.InternalStatemachineParser typedParser = (org.xtext.example.statemachine.ui.contentassist.antlr.internal.InternalStatemachineParser) parser;
			typedParser.entryRuleStatemachine();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public StatemachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StatemachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
