/*
* generated by Xtext
*/
package org.xtext.example.statemachine;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class StatemachineUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.example.statemachine.ui.internal.StatemachineActivator.getInstance().getInjector("org.xtext.example.statemachine.Statemachine");
	}
	
}
