/*
 * generated by Xtext
 */
package org.xtext.example.statemachine.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatemachineUiModule extends org.xtext.example.statemachine.ui.AbstractStatemachineUiModule {
	public StatemachineUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
